In [24]:
import pandas as pd
import numpy as np


pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

## Loading main dataset of primary metrics

In [25]:
df = pd.read_csv('../../DATA/MODEL/primary_features_df.csv')

# priamry_processed_values = ['CA','CASH','CL','EQ','NCL','TA','TL','CC','INV','CF_NETTO','CF_SELFFIN','EAT','EBIT','SAL','COST','INT','YIE']

# df = df[['financial_report_id', 'financial_report_template_id'] + priamry_processed_values]

# display(df.query('SAL >= 50000').iloc[:, 2:].describe().T)

## Computing secondary metrics - financial ratios

In [26]:
def get_ratios(row):
    row['L3'] = ( row['CA'] ) / ( row['CL'] ) if row['CL'] > 0 else None
    row['L2'] = ( row['CASH']+row['CC'] ) / ( row['CL'] ) if row['CL'] > 0 else None
    row['L1'] = ( row['CASH'] ) / ( row['CL'] ) if row['CL'] > 0 else None
    row['CF_CL'] = ( row['CF_NETTO'] ) / ( row['CL'] ) if row['CL'] > 0 else None
    row['CASH_TA'] = ( row['CASH'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['SAL_TA'] = ( row['SAL'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['TL_SAL'] = ( row['TL'] ) / ( row['SAL'] ) if row['SAL'] > 0 else None
    row['INV_COST'] = ( row['INV'] * 360 ) / ( row['COST'] ) if row['COST'] > 0 else None
    row['INV_SAL'] = ( row['INV'] * 360 ) / ( row['SAL'] ) if row['SAL'] > 0 else None
    row['CC_SAL'] = ( row['CC'] ) / ( row['SAL'] ) if row['SAL'] > 0 else None
    row['TA_SAL'] = ( row['TA'] * 360 ) / ( row['SAL'] ) if row['SAL'] > 0 else None
    row['TL_TA'] = ( row['TL'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['CF_TL'] = ( row['CF_NETTO'] ) / ( row['TL'] ) if row['TL'] > 0 else None
    row['CL_TA'] = ( row['CL'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['NCL_TA'] = ( row['NCL'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['EQ_TL'] = ( row['EQ'] ) / ( row['TL'] ) if row['TL'] > 0 else None
    row['EQ_TA'] = ( row['EQ'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['EBIT_INT'] = ( row['EBIT']+row['INT'] ) / ( row['INT'] ) if row['INT'] > 0 else None
    row['CL_CC'] = ( row['CL'] ) / ( row['CC'] ) if row['CC'] > 0 else None
    row['ROE'] = ( row['EAT'] ) / ( row['EQ'] ) if row['EQ'] > 0 else None
    row['EAT_TA'] = ( row['EAT'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['ROA_BRUTTO'] = ( row['EBIT'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['CF_TA'] = ( row['CF_NETTO'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['CF_SAL'] = ( row['CF_NETTO'] ) / ( row['SAL'] ) if row['SAL'] > 0 else None
    row['ROS'] = ( row['EAT'] ) / ( row['SAL'] ) if row['SAL'] > 0 else None
    row['EAT_YIE'] = ( row['EAT'] ) / ( row['YIE'] ) if row['YIE'] > 0 else None
    row['ROI'] = ( row['EAT']+row['INT'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['ROA_NETTO'] = ( row['EAT'] ) / ( row['TA'] ) if row['TA'] > 0 else None

    row['LABOR_PRODUCTIVITY'] = row['personnel_costs'] / ( row['SAL'] ) if row['SAL'] > 0 else None
    row['SOCLIAB_SAL'] = row['liabilities_to_employees_and_social_insurance'] / ( row['SAL'] ) if row['SAL'] > 0 else None

    return row


records = []
k = 0
size = df.shape[0]

for row_dict in df.to_dict(orient="records"):
    # if k >= 100:
    #     break

    if (k + 1) % 50000 == 0:
        print(f'{k + 1} / {size}')

    k += 1

    records.append(get_ratios(row_dict))


df_extended = pd.DataFrame(records)

ratios = ['CF_NETTO', 'CF_SELFFIN', 'EAT', 'EBIT', 'SAL', 'COST', 'INT', 'YIE',
       'L3', 'L2', 'L1', 'CF_CL', 'CASH_TA', 'SAL_TA', 'TL_SAL', 'INV_COST',
       'INV_SAL', 'CC_SAL', 'TA_SAL', 'TL_TA', 'CF_TL', 'CL_TA', 'NCL_TA',
       'EQ_TL', 'EQ_TA', 'EBIT_INT', 'CL_CC', 'ROE', 'EAT_TA', 'ROA_BRUTTO',
       'CF_TA', 'CF_SAL', 'ROS', 'EAT_YIE', 'ROI', 'ROA_NETTO',
       'LABOR_PRODUCTIVITY', 'SOCLIAB_SAL']


df_extended[ratios].describe().T

50000 / 1763209
100000 / 1763209
150000 / 1763209
200000 / 1763209
250000 / 1763209
300000 / 1763209
350000 / 1763209
400000 / 1763209
450000 / 1763209
500000 / 1763209
550000 / 1763209
600000 / 1763209
650000 / 1763209
700000 / 1763209
750000 / 1763209
800000 / 1763209
850000 / 1763209
900000 / 1763209
950000 / 1763209
1000000 / 1763209
1050000 / 1763209
1100000 / 1763209
1150000 / 1763209
1200000 / 1763209
1250000 / 1763209
1300000 / 1763209
1350000 / 1763209
1400000 / 1763209
1450000 / 1763209
1500000 / 1763209
1550000 / 1763209
1600000 / 1763209
1650000 / 1763209
1700000 / 1763209
1750000 / 1763209

,count,mean,std,min,25%,50%,75%,max
CF_NETTO,1763209.0,52056.263993,8.662394e+05,-1.856062e+08,-116.000000,2270.000000,16529.000000,2.995041e+08
CF_SELFFIN,1763209.0,45755.347963,8.473785e+05,-1.856062e+08,-480.000000,1780.000000,14476.000000,2.995012e+08
EAT,1763209.0,18692.317924,7.541622e+05,-1.856062e+08,-1130.000000,493.000000,6913.000000,2.995012e+08
EBIT,1763209.0,26329.236008,7.948221e+05,-1.856062e+08,-780.000000,888.000000,8730.000000,2.995041e+08
SAL,1763209.0,683802.999623,7.299065e+06,-3.049693e+07,4000.000000,36797.000000,160424.000000,1.708491e+09
COST,1763209.0,712780.732116,7.804105e+06,-7.599873e+07,5612.000000,36862.000000,164869.000000,1.645877e+09
INT,1763209.0,9067.491379,2.758140e+05,-4.531890e+05,0.000000,0.000000,343.000000,8.720448e+07
YIE,1763209.0,739110.216345,7.979590e+06,-3.049693e+07,5010.000000,39318.000000,171748.000000,1.708499e+09
L3,1609284.0,36.243925,5.865823e+03,-1.939807e+04,0.779430,1.744192,5.782889,6.632828e+06
L2,1609284.0,34.187229,5.814287e+03,-1.939807e+04,0.540963,1.499037,5.348945,6.632828e+06
L1,1609284.0,17.459562,1.100034e+03,-1.939807e+04,0.111999,0.683712,3.411639,6.758690e+05
CF_CL,1609284.0,-1.735890,3.876456e+03,-4.828154e+06,-0.011653,0.171098,1.047929,4.104870e+05
CASH_TA,1717851.0,0.499896,6.410686e+01,-4.790000e+02,0.077998,0.343102,0.818095,8.350930e+04
SAL_TA,1717851.0,3.677444,3.786158e+02,-5.020000e+02,0.167335,0.918777,1.992129,3.457260e+05
TL_SAL,1440480.0,400.439286,7.249368e+04,-5.873311e+03,0.145567,0.373632,1.066667,4.089693e+07
INV_COST,1611669.0,2668.888301,4.054020e+05,-2.143800e+06,0.000000,0.000000,8.911029,2.958960e+08
INV_SAL,1440480.0,28284.987459,1.230825e+07,-2.641140e+06,0.000000,0.000000,12.780004,1.262517e+10
CC_SAL,1440480.0,84.119425,2.177640e+04,-6.313000e+03,0.031569,0.123372,0.315686,1.351931e+07
TA_SAL,1440480.0,170601.502991,2.819145e+07,-2.669760e+06,156.825327,299.916982,685.341358,1.379876e+10
TL_TA,1717851.0,54.898264,2.970148e+04,-1.170720e+04,0.152971,0.551570,0.923517,3.732389e+07
CF_TL,1626183.0,-1.968576,3.822741e+03,-4.828154e+06,-0.009807,0.112978,0.615485,2.020956e+05
CL_TA,1717851.0,50.424752,2.965509e+04,-1.190400e+04,0.089299,0.327396,0.761382,3.731080e+07
NCL_TA,1717851.0,4.473512,1.057878e+03,-7.485250e+03,0.000000,0.006358,0.159821,6.519300e+05
EQ_TL,1626183.0,34.982844,2.926800e+03,-1.939907e+04,0.050791,0.631821,3.680256,1.984696e+06
EQ_TA,1717851.0,-53.913856,2.970151e+04,-3.732389e+07,0.072783,0.440366,0.844434,1.170820e+04
EBIT_INT,696210.0,1253.711310,1.126538e+05,-4.740091e+07,-1.592642,4.879204,50.632040,4.586330e+07
CL_CC,1382967.0,208.411662,5.697015e+04,-8.213780e+05,0.668960,1.679913,6.175037,6.510560e+07
ROE,1401809.0,-0.829745,1.068952e+02,-2.749900e+04,-0.022100,0.075902,0.289080,6.515051e+04
EAT_TA,1717851.0,-7.769434,7.143998e+03,-9.322502e+06,-0.048803,0.011024,0.114147,1.015460e+05
ROA_BRUTTO,1717851.0,-7.618072,7.143995e+03,-9.322502e+06,-0.030028,0.018601,0.145947,1.020260e+05
CF_TA,1717851.0,-7.769515,7.149003e+03,-9.322502e+06,-0.007221,0.058414,0.208668,6.515051e+04
CF_SAL,1440480.0,-8.857743,9.356169e+03,-4.298885e+06,0.004864,0.078604,0.244634,4.916876e+06
ROS,1440480.0,-12.466595,8.639847e+03,-4.298885e+06,-0.037217,0.024975,0.122766,3.862550e+06
EAT_YIE,1485909.0,-114.299582,4.467517e+04,-4.740188e+07,-0.046785,0.022644,0.117858,1.430609e+06
ROI,1717851.0,-7.696977,7.143878e+03,-9.322483e+06,-0.043731,0.017579,0.119853,1.015460e+05
ROA_NETTO,1717851.0,-7.769434,7.143998e+03,-9.322502e+06,-0.048803,0.011024,0.114147,1.015460e+05
LABOR_PRODUCTIVITY,1440480.0,0.752050,1.440396e+02,-1.516667e+02,0.000000,0.058333,0.214637,1.013800e+05
SOCLIAB_SAL,1440480.0,0.355697,1.278379e+02,-2.800000e+02,0.000000,0.003784,0.018324,1.059450e+05

## Joining meta information (dimensions) about financial statements

In [27]:
statements_reports_table = pd.read_csv('../../DATA/TRANSFORM/financial_statements/financial_statements_reports_table.csv')
statements_table = pd.read_csv('../../DATA/TRANSFORM/financial_statements/financial_statements_table.csv')
entity_details_table = pd.read_csv('../../DATA/TRANSFORM/entity_details/financial_statements_register_entity_details.csv')

C:\Users\matus.rohal\AppData\Roaming\Python\Python310\site-packages\IPython\core\interactiveshell.py:3433: DtypeWarning: Columns (14,15) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\matus.rohal\AppData\Roaming\Python\Python310\site-packages\IPython\core\interactiveshell.py:3433: DtypeWarning: Columns (13,15,16,17,18) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [28]:
entity_details_table = entity_details_table[['id', 'establishment_date', 'sknace_code', 'entity_state']].rename(columns={'id': 'entity_id'})

statements_table = statements_table[['financial_statement_id', 'entity_id', 'entity_ico', 'year', 'month', 'period_length', 'consolidated', 'approved_date', 'type', 'entity_name']]

display(df_extended.shape[0])

df_statements_extended = (df_extended
                          .drop_duplicates('financial_report_id')
                          .merge(
                              statements_reports_table.drop_duplicates('financial_report_id'),
                              on = 'financial_report_id',
                              how = 'left')
                          .merge(
                              statements_table,
                              on = 'financial_statement_id',
                              how = 'left')
                          .merge(
                              entity_details_table.drop_duplicates('entity_id'),
                              on = 'entity_id',
                              how = 'left'))

df_statements_extended = df_statements_extended

display(df_statements_extended.shape[0])

statements_reports_table = None
statements_table = None
entity_details_table = None

1763209

1763149

In [29]:
df_statements_extended.query('period_length == 12', inplace=True)
df_statements_extended.query('SAL >= 50000', inplace=True)

In [30]:
display(df_statements_extended.shape)

df_statements_extended = (df_statements_extended
                          .query('2014 <= year <= 2021')
                          .sort_values(['approved_date', 'TA', 'SAL'], ascending=[False, False, False])
                          .groupby(['entity_ico', 'year']).first()
                          .reset_index())

df_statements_extended

display(df_statements_extended.shape)

(744380, 140)

(708425, 140)

In [31]:
df_statements_extended = df_statements_extended[
    ['financial_report_id', 'financial_statement_id',
     'financial_report_order_number', 'entity_id', 'approved_date',
     'entity_ico', 'year', 'month', 'financial_report_template_id',
     'entity_name', 'establishment_date', 'sknace_code', 'entity_state',

    'financial_report_id',
    'financial_report_template_id',
    'total_assets',
    'non_current_assets',
    'intangible_assets',
    'total_non_current_tangible_assets',
    'land_and_buildings',
    'separate_movable_assets_and_sets_of_movable_assets',
    'other_long_term_tangible_assets',
    'adjustment_item_for_acquired_assets',
    'total_long_term_financial_assets',
    'bank_balances_with_maturity_longer_than_one_year',
    'current_assets',
    'inventories',
    'non_current_claims',
    'current_claims',
    'trade_receivables',
    'social_security_tax_receivables_and_grants',
    'financial_assets',
    'other_financial_accounts',
    'cash_and_bank_balances',

    'total_owners_equity_and_liabilities',
    'owners_equity',
    'share_capital',
    'share_capital_and_changes_in_share_capital',
    'claims_for_subscribed_owners_equity',
    'capital_funds',
    'valuation_differences',
    'undivided_profit_or_unpaid_loss_from_previous_years',
    'profit_for_the_reporting_period_after_tax',
    'liabilities',
    'long_term_liabilities_excluding_reserves_and_loans',
    'long_term_reserves',
    'long_term_bank_loans',
    'total_short_term_liabilities_excluding_reserves_loans_and_advances',
    'short_term_trade_liabilities',
    'liabilities_to_employees_and_social_insurance',
    'tax_liabilities_and_grants',
    'short_term_reserves',
    'current_bank_loans',
    'total_operating_revenue',
    'sales_revenue',
    'revenue_from_the_sale_of_own_products_and_services',
    'change_in_intra_organizational_inventories',
    'activation',
    'revenue_from_the_sale_of_long_term_intangible_assets_long_term_tangible_assets_and_materials',
    'other_revenues_from_operating_activities',
    'total_operating_costs',
    'costs_incurred_to_acquire_sold_goods',
    'consumption_of_materials_energy_and_other_non_inventory_supplies',
    'services',
    'personnel_costs',
    'taxes_and_fees',
    'depreciation_and_adjustments_to_long_term_intangible_assets_and_long_term_tangible_assets',
    'remaining_cost_of_sold_long_term_assets_and_materials',
    'adjustments_to_receivables',
    'other_costs_of_operating_activities',
    'operating_result_from_operating_activities',
    'value_added',
    'total_financial_revenues',
    'revenue_from_the_sale_of_securities_and_shares',
    'revenue_from_long_term_financial_assets',
    'revenue_from_short_term_financial_assets',
    'interest_income',
    'exchange_gains',
    'other_revenues_from_financial_activities',
    'total_financial_costs', 'sale_of_securities_and_shares',
    'costs_of_short_term_financial_assets',
    'adjustments_to_financial_assets',
    'interest_expenses',
    'exchange_losses',
    'other_costs_of_financial_activities',
    'financial_result',
    'result_of_operations_for_the_reporting_period_before_tax',
    'income_tax',
    'transfer_of_shares_in_the_result_to_shareholders',
    'result_of_operations_for_the_reporting_period_after_tax',
     
     'CA', 'CASH', 'CL', 'EQ', 'NCL', 'TA', 'TL',
     'CC', 'INV', 'CF_NETTO', 'CF_SELFFIN', 'EAT', 'EBIT', 'SAL', 'COST',
     'INT', 'YIE',
     
     'L3', 'L2', 'L1', 'CF_CL', 'CASH_TA', 'SAL_TA', 'TL_SAL',
     'INV_COST', 'INV_SAL', 'CC_SAL', 'TA_SAL', 'TL_TA', 'CF_TL', 'CL_TA',
     'NCL_TA', 'EQ_TL', 'EQ_TA', 'EBIT_INT', 'CL_CC', 'ROE', 'EAT_TA',
     'ROA_BRUTTO', 'CF_TA', 'CF_SAL', 'ROS', 'EAT_YIE', 'ROI', 'ROA_NETTO',
       'LABOR_PRODUCTIVITY', 'SOCLIAB_SAL'
     ]
]

df_statements_extended
df = None
df_extended = None

## Joining SKNACE codebook

In [32]:
codebook_sknace_raw = pd.read_csv('../../DATA/RAW/register_uz_apr23/preprocessed/codebook_sk-nace.csv')
codebook_sknace_divisions_raw = pd.read_csv('../../DATA/RAW/register_uz_apr23/preprocessed/codebook_sk-nace_divisions_su.csv', sep= '|')


codebook_sknace = codebook_sknace_raw[['kod', 'nazov.sk']]
codebook_sknace.columns = ['sknace_code', 'sknace_group']

codebook_sknace['sknace_code'] = pd.to_numeric(codebook_sknace['sknace_code'])
codebook_sknace['sknace_division_code'] = codebook_sknace['sknace_code'].apply(lambda x: x//1000)

# display(codebook_sknace)
# display(codebook_sknace_divisions_raw)

codebook_sknace_divisions = codebook_sknace_divisions_raw[['code', 'officialTitle', 'note']]
codebook_sknace_divisions.columns = ['sknace_division_code', 'sknace_division_name', 'sknace_division']
codebook_sknace_divisions['sknace_division_code'] = pd.to_numeric(codebook_sknace_divisions['sknace_division_code'])

codebook_sknace = codebook_sknace.merge(codebook_sknace_divisions, on = 'sknace_division_code', how = 'left')

codebook_sknace

C:\Users\matus.rohal\AppData\Local\Temp\ipykernel_3868\932557765.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  codebook_sknace['sknace_code'] = pd.to_numeric(codebook_sknace['sknace_code'])
C:\Users\matus.rohal\AppData\Local\Temp\ipykernel_3868\932557765.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  codebook_sknace_divisions['sknace_division_code'] = pd.to_numeric(codebook_sknace_divisions['sknace_division_code'])

,sknace_code,sknace_group,sknace_division_code,sknace_division_name,sknace_division
0,1110,Pestov.obilnín,1,"Pestovanie plodín a chov zvierat, poľovníctvo ...",A
1,1120,Pestov.ryže,1,"Pestovanie plodín a chov zvierat, poľovníctvo ...",A
2,1130,"Pestov.zeleniny,melónov",1,"Pestovanie plodín a chov zvierat, poľovníctvo ...",A
3,1140,Pestov.cukrovej trstiny,1,"Pestovanie plodín a chov zvierat, poľovníctvo ...",A
4,1150,Pestov.tabaku,1,"Pestovanie plodín a chov zvierat, poľovníctvo ...",A
...,...,...,...,...,...
641,96090,Ost.osob.služby i.n.,96,Ostatné osobné služby,S
642,97000,Čin.domácn.ako zamestn.,97,Činnosti domácností ako zamestnávateľov domáce...,T
643,98100,Čin.v dom.produk.tovary,98,Nediferencované činnosti v domácnostiach produ...,T
644,98200,Čin.v dom.produk.služby,98,Nediferencované činnosti v domácnostiach produ...,T
645,99000,Čin.extrateritoriál.org.,99,Činnosti extrateritoriálnych organizácií a zdr...,U

In [33]:
merged_df = df_statements_extended.merge(codebook_sknace[['sknace_code', 'sknace_division_name', 'sknace_division']], on = 'sknace_code', how = 'left')
merged_df['sknace_subcategory'] = merged_df['sknace_code'] // 1000

# display(merged_df['sknace_subcategory'].value_counts().to_frame())

In [34]:
merged_df

,financial_report_id,financial_statement_id,financial_report_order_number,entity_id,approved_date,entity_ico,year,month,financial_report_template_id,entity_name,establishment_date,sknace_code,entity_state,financial_report_id,financial_report_template_id,total_assets,non_current_assets,intangible_assets,total_non_current_tangible_assets,land_and_buildings,separate_movable_assets_and_sets_of_movable_assets,other_long_term_tangible_assets,adjustment_item_for_acquired_assets,total_long_term_financial_assets,bank_balances_with_maturity_longer_than_one_year,current_assets,inventories,non_current_claims,current_claims,trade_receivables,social_security_tax_receivables_and_grants,financial_assets,other_financial_accounts,cash_and_bank_balances,total_owners_equity_and_liabilities,owners_equity,share_capital,share_capital_and_changes_in_share_capital,claims_for_subscribed_owners_equity,capital_funds,valuation_differences,undivided_profit_or_unpaid_loss_from_previous_years,profit_for_the_reporting_period_after_tax,liabilities,long_term_liabilities_excluding_reserves_and_loans,long_term_reserves,long_term_bank_loans,total_short_term_liabilities_excluding_reserves_loans_and_advances,short_term_trade_liabilities,liabilities_to_employees_and_social_insurance,...,CA,CASH,CL,EQ,NCL,TA,TL,CC,INV,CF_NETTO,CF_SELFFIN,EAT,EBIT,SAL,COST,INT,YIE,L3,L2,L1,CF_CL,CASH_TA,SAL_TA,TL_SAL,INV_COST,INV_SAL,CC_SAL,TA_SAL,TL_TA,CF_TL,CL_TA,NCL_TA,EQ_TL,EQ_TA,EBIT_INT,CL_CC,ROE,EAT_TA,ROA_BRUTTO,CF_TA,CF_SAL,ROS,EAT_YIE,ROI,ROA_NETTO,LABOR_PRODUCTIVITY,SOCLIAB_SAL,sknace_division_name,sknace_division,sknace_subcategory
0,4593745,2340588,1,16410,2015-06-11,698.0,2014,1,699.0,"TECHNOPOL, a.s.",1970-02-18,70220.0,None,4593745,699.0,21085611.0,19528311.0,3680.0,21922.0,0.0,3254.0,18668.0,0.0,19502709.0,0.0,1543495.0,352.0,0.0,1227526.0,2900.0,0.0,315617.0,0.0,315617.0,21085611.0,17186564.0,166000.0,166000.0,0.0,13687667.0,3608126.0,3608126.0,-275229.0,3899047.0,65289.0,0.0,0.0,3796505.0,55151.0,10861.0,...,1543495.0,315617.0,3796505.0,17186564.0,102542.0,21085611.0,3899047.0,1227526.0,352.0,-245840.0,-246827.0,-275229.0,-274242.0,282838.0,611268.0,51413.0,337026.0,0.406557,0.406464,0.083134,-0.064754,0.014968,0.013414,13.785443,0.207307,0.448030,4.340032,26838.048494,0.184915,-0.063051,0.180052,0.004863,4.407888,0.815085,-4.334098,3.092810,-0.016014,-0.013053,-0.013006,-0.011659,-0.869190,-0.973098,-0.816640,-0.010615,-0.013053,0.688878,0.038400,Vedenie firiem; poradenstvo v oblasti riadenia,M,70.0
1,5107771,2744582,2,16410,2016-05-23,698.0,2015,1,699.0,"TECHNOPOL, a.s.",1970-02-18,70220.0,None,5107771,699.0,21924517.0,19315150.0,9603.0,5379.0,0.0,3052.0,2327.0,0.0,19300168.0,0.0,2600439.0,166.0,0.0,2018671.0,1433.0,0.0,581602.0,0.0,581602.0,21924517.0,16793364.0,166000.0,166000.0,0.0,15288565.0,1368126.0,1368126.0,-29327.0,5131153.0,5075794.0,0.0,0.0,43344.0,3154.0,20292.0,...,2600439.0,581602.0,43344.0,16793364.0,5087809.0,21924517.0,5131153.0,2018671.0,166.0,-6611.0,-7617.0,-29327.0,-28321.0,282672.0,367333.0,54368.0,339012.0,59.995363,59.991533,13.418282,-0.152524,0.026527,0.012893,18.152321,0.162686,0.211411,7.141390,27922.207081,0.234037,-0.001288,0.001977,0.232060,3.272825,0.765963,0.479087,0.021472,-0.001746,-0.001338,-0.001292,-0.000302,-0.023388,-0.103749,-0.086507,0.001142,-0.001338,0.820198,0.071786,Vedenie firiem; poradenstvo v oblasti riadenia,M,70.0
2,5623456,3158922,2,16410,2017-05-18,698.0,2016,1,699.0,"TECHNOPOL, a.s.",1970-02-18,70220.0,None,5623456,699.0,20214015.0,17519637.0,4719.0,2010.0,0.0,2010.0,0.0,0.0,17512908.0,0.0,2686285.0,122.0,0.0,2045962.0,924.0,0.0,640201.0,0.0,640201.0,20214015.0,15620952.0,166000.0,166000.0,0.0,13474528.0,1368126.0,1368126.0,612298.0,4593063.0,47267.0,0.0,0.0,4536337.0,2086.0,9106.0,...,2686285.0,640201.0,4536337.0,15620952.0,56726.0,20214015.0,4593063.0,2045962.0,122.0,623491.0,620551.0,612298.0,615238.0,183223.0,217545.0,28117.0,832783.0,0.592171,0.592144,0.141127,0.137444,0.031671,0.009064,25.068157,0.201889,0.239708,11.166513,39716.877248,0.227222,0.135746,0.224415,0.002806,3.400988,0.772778,22.881353,2.217215,0.039197,0.030291,0.030436,0.030844,3.402908,3.341818,0.735243,0.031682,0.030291,0.652565,0.049699,Vedenie firiem; poradenstvo v oblasti riadenia,M,70.0
3,6119223,3557660,1,16410,2018-06-05,698.0,2017,1,699.0,"TECHNOPOL, a.s.",1970-02-18,70220.0,None,6119223,699.0,17937814.0,14997149.0,8821.0,7460.0,0.0,968.0,0.0,0.0,14980868.0,0.0,2929543.0,38.0,0.0,2627415.0,52549.0,0.0,302090.0,0.0,302090.0,17937814.0,13611581.0,166000.0,166000.0,0.0,11442488.0,1980424.0,1980424.0,22669.0,4326233.0,38384.0,0.0,0.0,4277153.0,5492.0,15253.0,...,2929543.0,302090.0,4277153.0,13611581.0,49080.0,17937814.0,4326233.0,2627415.0,38.0,28755.0,27777.0,22669.0,23647.0,180105.0,237265.0,29922.0,260912.0,0.684928,0.684919,0.070629,0.006723,0.016841,0.010041,24.020616,0.057657,0.075956,14.588240,35854.712751,0.241179,0.006647,0.238443,0.002736,3.146289,0.758821,1.790288,1.627894,0.001665,0.001264,0.001318,0.001603,0.159657,0.125865,0.086884,0.002932,0.001264,0.791205,0.084689,Vedenie firiem; poradenstvo v oblasti riadenia,M,70.0
4,6583487,3932125,2,16410,2019-06-05,698.0,2018,1,699.0,"TECHNOPOL, a.s.",1970-02-18,70220.0,None,6583487,699.0,16830758.0,11751570.0,6353.0,9101.0,0.0,9101.0,0.0,0.0,11736116.0,0.0,5068652.0,59.0,3250.0,4445469.0,840.0,0.0,619874.0,0.0,619874.0,16830758.0,13247220.0,166000.0,166000.0,0.0,10643195.0,2003093.0,2003093.0,434932.0,3583538.0,29782.0,316.0,0.0,3547183.0,13183.0,7602.0,...,5065402.0,619874.0,3547183.0,13247220.0,36355.0,16830758.0,3583538.0,4445469.0,59.0,14095.0,13634.0,434932.0,435393.0,186562.0,-187117.0,61152.0,248276.0,1.428007,1.427990,0.174751,0.003974,0.036830,0.011085,19.208295,NaN,0.113850,23.828373,32477.529615,0.212916,0.003933,0.210756,0.002160,3.696687,0.787084,8.119849,0.797932,0.032832,0.025841,0.025869,0.000837,0.075551,2.331300,1.751808,0.029475,0.025841,0.743158,0.040748,Vedenie firiem; poradenstvo v oblasti riadenia,M,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
708420,8064601,5126827,1,2028338,2022-04-07,54228875.0,2021,1,687.0,Propyro fireworks s. r. o.,2021-11-23,47789.0,None,8064601,687.0,71862.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,71862.0,13860.0,0.0,8289.0,0.0,0.0,49713.0,0.0,49713.0,71862.0,5522.0,5000.0,5000.0,0.0,0.0,0.0,0.0,522.0,66340.0,0.0,0.0,0.0,66340.0,65931.0,247.0,...,71862.0,49713.0,66340.0,5522.0,0.0,71862.0,66340.0,8289.0,13860.0,661.0,522.0,522.0,661.0,54505.0,53844.0,0.0,54505.0,1.083238,0.874314,0.749367,0.009964,0.691784,0.758468,1.217136,92.667707,91.543895,0.152078,474.641226,0.923158,0.009964,0.923158,0.000000,0.083238,0.076842,NaN,8.003378,0.094531,0.007264,0.009198,0.009198,0.012127,0.009577,0.009577,0.007264,0.007264,0.004954,0.004532,Maloobchod okrem motorových vozidiel a motocyklov,G,47.0
708421,8222657,5259246,1,2035250,None,54268681.0,2021,1,687.0,Elektromont LS s. r. o.,2021-12-10,71121.0,None,8222657,687.0,148772.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,148772.0,0.0,0.0,141472.0,141472.0,0.0,7300.0,0.0,7300.0,148772.0,73063.0,5000.0,5000.0,0.0,0.0,0.0,0.0,68063.0,75709.0,0.0,0.0,0.0,33709.0,15617.0,0.0,...,148772.0,7300.0,33709.0,73063.0,42000.0,148772.0,75709.0,141472.0,0.0,86155.0,68063.0,68063.0,86155.0,141472.0,55317.0,0.0,141472.0,4.413421,4.413421,0.216559,2.555846,0.049068,0.950932,0.535152,0.000000,0.000000,1.000000,378.576114,0.508893,1.137976,0.226582,0.282311,0.965050,0.491107,NaN,0.238273,0.931566,0.457499,0.579108,0.579108,0.608990,0.481106,0.481106,0.457499,0.457499,0.000000,0.000000,Architektonické a inžinierske činnosti; techni...,M,71.0
708422,4458450,2225050,1,289353,2015-02-27,60748940.0,2014,1,699.0,VALPEX s.r.o.,1991-07-17,46900.0,None,4458450,699.0,69884.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,69384.0,0.0,0.0,21566.0,21566.0,0.0,47818.0,0.0,47818.0,69884.0,-5515.0,0.0,0.0,0.0,0.0,-3797.0,-3797.0,-1718.0,75399.0,70059.0,0.0,0.0,5008.0,279.0,1212.0,...,69384.0,47818.0,5008.0,-5515.0,70391.0,69884.0,75399.0,21566.0,0.0,-758.0,-1718.0,-1718.0,-758.0,174779.0,179373.0,2.0,178615.0,13.854633,13.854633,9.548323,-0.151358,0.684248,2.500987,0.431396,0.000000,0.000000,0.123390,143.943151,1.078916,-0.010053,0.071662,1.007255,-0.073144,-0.078916,-378.000000,0.232217,NaN,-0.024584,-0.010847,-0.010847,-0.004337,-0.009830,-0.009618,-0.024555,-0.024584,0.095681,0.006934,"Veľkoobchod, okrem motorových vozidiel a motoc...",G,46.0
708423,5030426,2678436,1,289353,2016-03-12,60748940.0,2015,1,699.0,VALPEX s.r.o.,1991-07-17,46900.0,None,5030426,699.0,30029.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29950.0,0.0,0.0,3989.0,3989.0,0.0,25961.0,0.0,25961.0,30029.0,-9614.0,0.0,0.0,0.0,0.0,-5515.0,-5515.0,-4099.0,39643.0,37633.0,0.0,0.0,2010.0,592.0,0.0,...,29950.0,25961.0,2010.0,-9614.0,37633.0,30029.0,39643.0,3989.0,0.0,-3139.0,-4099.0,-4099.0,-3139.0,120316.0,126841.0,3.0,123702.0,14.900498,14.900498,12.915920,-1.561692,0.864531,4.006660,0.329491,0.000000,0.000000,0.033154,89.850394,1.320157,-0.079182,0.066935,1.253222,-0.242514,-0.320157,-1045.333333,0.503886,NaN,-0.136501,-0.104532,-0.104532,-0.026090,-0.034069,-0.033136,-0.136401,-0.136501,0.074570,0.000000,"Veľkoobchod, okrem motorových vozidiel a motoc...",G,46.0
708424,4673569,2406230,1,1040443,None,63987538.0,2014,1,687.0,VTS Czech Republic s.r.o.,1999-01-21,74900.0,None,4673569,687.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23144.0,23144.0,23144.0,23144.0,755840.0,732696.0,0.0,755840.0,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.030620,0.030620,0.030620,NaN,NaN,0.076438,0.000000,"Ostatné odborné, vedecké a technické činnosti",M,74.0

In [23]:
merged_df.to_csv('../../DATA/MODEL/financial_ratios_df.csv', index = False)