In [12]:
import pandas as pd
import numpy as np


pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

## Loading main dataset of primary metrics

In [13]:
df = pd.read_csv('../../DATA/MODEL/primary_features_df.csv')

# priamry_processed_values = ['CA','CASH','CL','EQ','NCL','TA','TL','CC','INV','CF_NETTO','CF_SELFFIN','EAT','EBIT','SAL','COST','INT','YIE']

# df = df[['financial_report_id', 'financial_report_template_id'] + priamry_processed_values]

# display(df.query('SAL >= 50000').iloc[:, 2:].describe().T)

## Computing secondary metrics - financial ratios

In [14]:
def get_ratios(row):
    row['L3'] = ( row['CA'] ) / ( row['CL'] ) if row['CL'] > 0 else None
    row['L2'] = ( row['CASH']+row['CC'] ) / ( row['CL'] ) if row['CL'] > 0 else None
    row['L1'] = ( row['CASH'] ) / ( row['CL'] ) if row['CL'] > 0 else None
    row['CF_CL'] = ( row['CF_NETTO'] ) / ( row['CL'] ) if row['CL'] > 0 else None
    row['CASH_TA'] = ( row['CASH'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['SAL_TA'] = ( row['SAL'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['TL_SAL'] = ( row['TL'] ) / ( row['SAL'] ) if row['SAL'] > 0 else None
    row['INV_COST'] = ( row['INV'] * 360 ) / ( row['COST'] ) if row['COST'] > 0 else None
    row['INV_SAL'] = ( row['INV'] * 360 ) / ( row['SAL'] ) if row['SAL'] > 0 else None
    row['CC_SAL'] = ( row['CC'] ) / ( row['SAL'] ) if row['SAL'] > 0 else None
    row['TA_SAL'] = ( row['TA'] * 360 ) / ( row['SAL'] ) if row['SAL'] > 0 else None
    row['TL_TA'] = ( row['TL'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['CF_TL'] = ( row['CF_NETTO'] ) / ( row['TL'] ) if row['TL'] > 0 else None
    row['CL_TA'] = ( row['CL'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['NCL_TA'] = ( row['NCL'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['EQ_TL'] = ( row['EQ'] ) / ( row['TL'] ) if row['TL'] > 0 else None
    row['EQ_TA'] = ( row['EQ'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['EBIT_INT'] = ( row['EBIT']+row['INT'] ) / ( row['INT'] ) if row['INT'] > 0 else None
    row['CL_CC'] = ( row['CL'] ) / ( row['CC'] ) if row['CC'] > 0 else None
    row['ROE'] = ( row['EAT'] ) / ( row['EQ'] ) if row['EQ'] > 0 else None
    row['EAT_TA'] = ( row['EAT'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['ROA_BRUTTO'] = ( row['EBIT'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['CF_TA'] = ( row['CF_NETTO'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['CF_SAL'] = ( row['CF_NETTO'] ) / ( row['SAL'] ) if row['SAL'] > 0 else None
    row['ROS'] = ( row['EAT'] ) / ( row['SAL'] ) if row['SAL'] > 0 else None
    row['EAT_YIE'] = ( row['EAT'] ) / ( row['YIE'] ) if row['YIE'] > 0 else None
    row['ROI'] = ( row['EAT']+row['INT'] ) / ( row['TA'] ) if row['TA'] > 0 else None
    row['ROA_NETTO'] = ( row['EAT'] ) / ( row['TA'] ) if row['TA'] > 0 else None

    row['LABOR_PRODUCTIVITY'] = row['personnel_costs'] / ( row['SAL'] ) if row['SAL'] > 0 else None
    row['SOCLIAB_SAL'] = row['liabilities_to_employees_and_social_insurance'] / ( row['SAL'] ) if row['SAL'] > 0 else None

    return row


records = []
k = 0
size = df.shape[0]

for row_dict in df.to_dict(orient="records"):
    # if k >= 100:
    #     break

    if (k + 1) % 50000 == 0:
        print(f'{k + 1} / {size}')

    k += 1

    records.append(get_ratios(row_dict))


df_extended = pd.DataFrame(records)

ratios = ['CF_NETTO', 'CF_SELFFIN', 'EAT', 'EBIT', 'SAL', 'COST', 'INT', 'YIE',
       'L3', 'L2', 'L1', 'CF_CL', 'CASH_TA', 'SAL_TA', 'TL_SAL', 'INV_COST',
       'INV_SAL', 'CC_SAL', 'TA_SAL', 'TL_TA', 'CF_TL', 'CL_TA', 'NCL_TA',
       'EQ_TL', 'EQ_TA', 'EBIT_INT', 'CL_CC', 'ROE', 'EAT_TA', 'ROA_BRUTTO',
       'CF_TA', 'CF_SAL', 'ROS', 'EAT_YIE', 'ROI', 'ROA_NETTO',
       'LABOR_PRODUCTIVITY', 'SOCLIAB_SAL']


df_extended[ratios].describe().T

50000 / 1763209
100000 / 1763209
150000 / 1763209
200000 / 1763209
250000 / 1763209
300000 / 1763209
350000 / 1763209
400000 / 1763209
450000 / 1763209
500000 / 1763209
550000 / 1763209
600000 / 1763209
650000 / 1763209
700000 / 1763209
750000 / 1763209
800000 / 1763209
850000 / 1763209
900000 / 1763209
950000 / 1763209
1000000 / 1763209
1050000 / 1763209
1100000 / 1763209
1150000 / 1763209
1200000 / 1763209
1250000 / 1763209
1300000 / 1763209
1350000 / 1763209
1400000 / 1763209
1450000 / 1763209
1500000 / 1763209
1550000 / 1763209
1600000 / 1763209
1650000 / 1763209
1700000 / 1763209
1750000 / 1763209

,count,mean,std,min,25%,50%,75%,max
CF_NETTO,1763209.0,52056.263993,8.662394e+05,-1.856062e+08,-116.000000,2270.000000,16529.000000,2.995041e+08
CF_SELFFIN,1763209.0,45755.347963,8.473785e+05,-1.856062e+08,-480.000000,1780.000000,14476.000000,2.995012e+08
EAT,1763209.0,18692.317924,7.541622e+05,-1.856062e+08,-1130.000000,493.000000,6913.000000,2.995012e+08
EBIT,1763209.0,26329.236008,7.948221e+05,-1.856062e+08,-780.000000,888.000000,8730.000000,2.995041e+08
SAL,1763209.0,683802.999623,7.299065e+06,-3.049693e+07,4000.000000,36797.000000,160424.000000,1.708491e+09
COST,1763209.0,712780.732116,7.804105e+06,-7.599873e+07,5612.000000,36862.000000,164869.000000,1.645877e+09
INT,1763209.0,9067.491379,2.758140e+05,-4.531890e+05,0.000000,0.000000,343.000000,8.720448e+07
YIE,1763209.0,739110.216345,7.979590e+06,-3.049693e+07,5010.000000,39318.000000,171748.000000,1.708499e+09
L3,1609284.0,36.243925,5.865823e+03,-1.939807e+04,0.779430,1.744192,5.782889,6.632828e+06
L2,1609284.0,34.187229,5.814287e+03,-1.939807e+04,0.540963,1.499037,5.348945,6.632828e+06
L1,1609284.0,17.459562,1.100034e+03,-1.939807e+04,0.111999,0.683712,3.411639,6.758690e+05
CF_CL,1609284.0,-1.735890,3.876456e+03,-4.828154e+06,-0.011653,0.171098,1.047929,4.104870e+05
CASH_TA,1717851.0,0.499896,6.410686e+01,-4.790000e+02,0.077998,0.343102,0.818095,8.350930e+04
SAL_TA,1717851.0,3.677444,3.786158e+02,-5.020000e+02,0.167335,0.918777,1.992129,3.457260e+05
TL_SAL,1440480.0,400.439286,7.249368e+04,-5.873311e+03,0.145567,0.373632,1.066667,4.089693e+07
INV_COST,1611669.0,2668.888301,4.054020e+05,-2.143800e+06,0.000000,0.000000,8.911029,2.958960e+08
INV_SAL,1440480.0,28284.987459,1.230825e+07,-2.641140e+06,0.000000,0.000000,12.780004,1.262517e+10
CC_SAL,1440480.0,84.119425,2.177640e+04,-6.313000e+03,0.031569,0.123372,0.315686,1.351931e+07
TA_SAL,1440480.0,170601.502991,2.819145e+07,-2.669760e+06,156.825327,299.916982,685.341358,1.379876e+10
TL_TA,1717851.0,54.898264,2.970148e+04,-1.170720e+04,0.152971,0.551570,0.923517,3.732389e+07
CF_TL,1626183.0,-1.968576,3.822741e+03,-4.828154e+06,-0.009807,0.112978,0.615485,2.020956e+05
CL_TA,1717851.0,50.424752,2.965509e+04,-1.190400e+04,0.089299,0.327396,0.761382,3.731080e+07
NCL_TA,1717851.0,4.473512,1.057878e+03,-7.485250e+03,0.000000,0.006358,0.159821,6.519300e+05
EQ_TL,1626183.0,34.982844,2.926800e+03,-1.939907e+04,0.050791,0.631821,3.680256,1.984696e+06
EQ_TA,1717851.0,-53.913856,2.970151e+04,-3.732389e+07,0.072783,0.440366,0.844434,1.170820e+04
EBIT_INT,696210.0,1253.711310,1.126538e+05,-4.740091e+07,-1.592642,4.879204,50.632040,4.586330e+07
CL_CC,1382967.0,208.411662,5.697015e+04,-8.213780e+05,0.668960,1.679913,6.175037,6.510560e+07
ROE,1401809.0,-0.829745,1.068952e+02,-2.749900e+04,-0.022100,0.075902,0.289080,6.515051e+04
EAT_TA,1717851.0,-7.769434,7.143998e+03,-9.322502e+06,-0.048803,0.011024,0.114147,1.015460e+05
ROA_BRUTTO,1717851.0,-7.618072,7.143995e+03,-9.322502e+06,-0.030028,0.018601,0.145947,1.020260e+05
CF_TA,1717851.0,-7.769515,7.149003e+03,-9.322502e+06,-0.007221,0.058414,0.208668,6.515051e+04
CF_SAL,1440480.0,-8.857743,9.356169e+03,-4.298885e+06,0.004864,0.078604,0.244634,4.916876e+06
ROS,1440480.0,-12.466595,8.639847e+03,-4.298885e+06,-0.037217,0.024975,0.122766,3.862550e+06
EAT_YIE,1485909.0,-114.299582,4.467517e+04,-4.740188e+07,-0.046785,0.022644,0.117858,1.430609e+06
ROI,1717851.0,-7.696977,7.143878e+03,-9.322483e+06,-0.043731,0.017579,0.119853,1.015460e+05
ROA_NETTO,1717851.0,-7.769434,7.143998e+03,-9.322502e+06,-0.048803,0.011024,0.114147,1.015460e+05
LABOR_PRODUCTIVITY,1440480.0,0.752050,1.440396e+02,-1.516667e+02,0.000000,0.058333,0.214637,1.013800e+05
SOCLIAB_SAL,1440480.0,0.355697,1.278379e+02,-2.800000e+02,0.000000,0.003784,0.018324,1.059450e+05

## Joining meta information (dimensions) about financial statements

In [15]:
statements_reports_table = pd.read_csv('../../DATA/TRANSFORM/financial_statements/financial_statements_reports_table.csv')
statements_table = pd.read_csv('../../DATA/TRANSFORM/financial_statements/financial_statements_table.csv')
entity_details_table = pd.read_csv('../../DATA/TRANSFORM/entity_details/financial_statements_register_entity_details.csv')

C:\Users\matus.rohal\AppData\Roaming\Python\Python310\site-packages\IPython\core\interactiveshell.py:3433: DtypeWarning: Columns (14,15) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\matus.rohal\AppData\Roaming\Python\Python310\site-packages\IPython\core\interactiveshell.py:3433: DtypeWarning: Columns (13,15,16,17,18) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [16]:
entity_details_table = entity_details_table[['id', 'establishment_date', 'cancellation_date', 'sknace_code', 'entity_state']].rename(columns={'id': 'entity_id'})

statements_table = statements_table[['financial_statement_id', 'entity_id', 'entity_ico', 'year', 'month', 'period_length', 'consolidated', 'approved_date', 'type', 'entity_name']]

display(df_extended.shape[0])

df_statements_extended = (df_extended
                          .drop_duplicates('financial_report_id')
                          .merge(
                              statements_reports_table.drop_duplicates('financial_report_id'),
                              on = 'financial_report_id',
                              how = 'left')
                          .merge(
                              statements_table,
                              on = 'financial_statement_id',
                              how = 'left')
                          .merge(
                              entity_details_table.drop_duplicates('entity_id'),
                              on = 'entity_id',
                              how = 'left'))

df_statements_extended = df_statements_extended

display(df_statements_extended.shape[0])

statements_reports_table = None
statements_table = None
entity_details_table = None

1763209

1763149

In [17]:
display(df_statements_extended.shape)

df_statements_extended = (df_statements_extended
                          .query('2014 <= year <= 2021')
                          .sort_values(['approved_date', 'TA', 'SAL'], ascending=[False, False, False])
                          .groupby(['entity_ico', 'year']).first()
                          .reset_index())

df_statements_extended

display(df_statements_extended.shape)

(1763149, 141)

(1679950, 141)

In [18]:
df_statements_extended = df_statements_extended[
    ['financial_report_id', 'financial_statement_id',
     'financial_report_order_number', 'entity_id', 'approved_date',
     'entity_ico', 'year', 'month', 'financial_report_template_id',
     'entity_name', 'establishment_date', 'cancellation_date', 'sknace_code', 'entity_state', 'period_length',

    'financial_report_id',
    'financial_report_template_id',
    'total_assets',
    'non_current_assets',
    'intangible_assets',
    'total_non_current_tangible_assets',
    'land_and_buildings',
    'separate_movable_assets_and_sets_of_movable_assets',
    'other_long_term_tangible_assets',
    'adjustment_item_for_acquired_assets',
    'total_long_term_financial_assets',
    'bank_balances_with_maturity_longer_than_one_year',
    'current_assets',
    'inventories',
    'non_current_claims',
    'current_claims',
    'trade_receivables',
    'social_security_tax_receivables_and_grants',
    'financial_assets',
    'other_financial_accounts',
    'cash_and_bank_balances',

    'total_owners_equity_and_liabilities',
    'owners_equity',
    'share_capital',
    'share_capital_and_changes_in_share_capital',
    'claims_for_subscribed_owners_equity',
    'capital_funds',
    'valuation_differences',
    'undivided_profit_or_unpaid_loss_from_previous_years',
    'profit_for_the_reporting_period_after_tax',
    'liabilities',
    'long_term_liabilities_excluding_reserves_and_loans',
    'long_term_reserves',
    'long_term_bank_loans',
    'total_short_term_liabilities_excluding_reserves_loans_and_advances',
    'short_term_trade_liabilities',
    'liabilities_to_employees_and_social_insurance',
    'tax_liabilities_and_grants',
    'short_term_reserves',
    'current_bank_loans',
    'total_operating_revenue',
    'sales_revenue',
    'revenue_from_the_sale_of_own_products_and_services',
    'change_in_intra_organizational_inventories',
    'activation',
    'revenue_from_the_sale_of_long_term_intangible_assets_long_term_tangible_assets_and_materials',
    'other_revenues_from_operating_activities',
    'total_operating_costs',
    'costs_incurred_to_acquire_sold_goods',
    'consumption_of_materials_energy_and_other_non_inventory_supplies',
    'services',
    'personnel_costs',
    'taxes_and_fees',
    'depreciation_and_adjustments_to_long_term_intangible_assets_and_long_term_tangible_assets',
    'remaining_cost_of_sold_long_term_assets_and_materials',
    'adjustments_to_receivables',
    'other_costs_of_operating_activities',
    'operating_result_from_operating_activities',
    'value_added',
    'total_financial_revenues',
    'revenue_from_the_sale_of_securities_and_shares',
    'revenue_from_long_term_financial_assets',
    'revenue_from_short_term_financial_assets',
    'interest_income',
    'exchange_gains',
    'other_revenues_from_financial_activities',
    'total_financial_costs', 'sale_of_securities_and_shares',
    'costs_of_short_term_financial_assets',
    'adjustments_to_financial_assets',
    'interest_expenses',
    'exchange_losses',
    'other_costs_of_financial_activities',
    'financial_result',
    'result_of_operations_for_the_reporting_period_before_tax',
    'income_tax',
    'transfer_of_shares_in_the_result_to_shareholders',
    'result_of_operations_for_the_reporting_period_after_tax',
     
     'CA', 'CASH', 'CL', 'EQ', 'NCL', 'TA', 'TL',
     'CC', 'INV', 'CF_NETTO', 'CF_SELFFIN', 'EAT', 'EBIT', 'SAL', 'COST',
     'INT', 'YIE',
     
     'L3', 'L2', 'L1', 'CF_CL', 'CASH_TA', 'SAL_TA', 'TL_SAL',
     'INV_COST', 'INV_SAL', 'CC_SAL', 'TA_SAL', 'TL_TA', 'CF_TL', 'CL_TA',
     'NCL_TA', 'EQ_TL', 'EQ_TA', 'EBIT_INT', 'CL_CC', 'ROE', 'EAT_TA',
     'ROA_BRUTTO', 'CF_TA', 'CF_SAL', 'ROS', 'EAT_YIE', 'ROI', 'ROA_NETTO',
       'LABOR_PRODUCTIVITY', 'SOCLIAB_SAL'
     ]
]

df_statements_extended
df = None
df_extended = None

## Joining SKNACE codebook

In [19]:
codebook_sknace_raw = pd.read_csv('../../DATA/RAW/register_uz_apr23/preprocessed/codebook_sk-nace.csv')
codebook_sknace_divisions_raw = pd.read_csv('../../DATA/RAW/register_uz_apr23/preprocessed/codebook_sk-nace_divisions_su.csv', sep= '|')


codebook_sknace = codebook_sknace_raw[['kod', 'nazov.sk']]
codebook_sknace.columns = ['sknace_code', 'sknace_group']

codebook_sknace['sknace_code'] = pd.to_numeric(codebook_sknace['sknace_code'])
codebook_sknace['sknace_division_code'] = codebook_sknace['sknace_code'].apply(lambda x: x//1000)

# display(codebook_sknace)
# display(codebook_sknace_divisions_raw)

codebook_sknace_divisions = codebook_sknace_divisions_raw[['code', 'officialTitle', 'note']]
codebook_sknace_divisions.columns = ['sknace_division_code', 'sknace_division_name', 'sknace_division']
codebook_sknace_divisions['sknace_division_code'] = pd.to_numeric(codebook_sknace_divisions['sknace_division_code'])

codebook_sknace = codebook_sknace.merge(codebook_sknace_divisions, on = 'sknace_division_code', how = 'left')

codebook_sknace

C:\Users\matus.rohal\AppData\Local\Temp\ipykernel_15104\932557765.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  codebook_sknace['sknace_code'] = pd.to_numeric(codebook_sknace['sknace_code'])
C:\Users\matus.rohal\AppData\Local\Temp\ipykernel_15104\932557765.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  codebook_sknace_divisions['sknace_division_code'] = pd.to_numeric(codebook_sknace_divisions['sknace_division_code'])

,sknace_code,sknace_group,sknace_division_code,sknace_division_name,sknace_division
0,1110,Pestov.obilnín,1,"Pestovanie plodín a chov zvierat, poľovníctvo ...",A
1,1120,Pestov.ryže,1,"Pestovanie plodín a chov zvierat, poľovníctvo ...",A
2,1130,"Pestov.zeleniny,melónov",1,"Pestovanie plodín a chov zvierat, poľovníctvo ...",A
3,1140,Pestov.cukrovej trstiny,1,"Pestovanie plodín a chov zvierat, poľovníctvo ...",A
4,1150,Pestov.tabaku,1,"Pestovanie plodín a chov zvierat, poľovníctvo ...",A
...,...,...,...,...,...
641,96090,Ost.osob.služby i.n.,96,Ostatné osobné služby,S
642,97000,Čin.domácn.ako zamestn.,97,Činnosti domácností ako zamestnávateľov domáce...,T
643,98100,Čin.v dom.produk.tovary,98,Nediferencované činnosti v domácnostiach produ...,T
644,98200,Čin.v dom.produk.služby,98,Nediferencované činnosti v domácnostiach produ...,T
645,99000,Čin.extrateritoriál.org.,99,Činnosti extrateritoriálnych organizácií a zdr...,U

In [20]:
merged_df = df_statements_extended.merge(codebook_sknace[['sknace_code', 'sknace_division_name', 'sknace_division']], on = 'sknace_code', how = 'left')
merged_df['sknace_subcategory'] = merged_df['sknace_code'] // 1000

# display(merged_df['sknace_subcategory'].value_counts().to_frame())

In [21]:
merged_df

,financial_report_id,financial_statement_id,financial_report_order_number,entity_id,approved_date,entity_ico,year,month,financial_report_template_id,entity_name,establishment_date,cancellation_date,sknace_code,entity_state,period_length,financial_report_id,financial_report_template_id,total_assets,non_current_assets,intangible_assets,total_non_current_tangible_assets,land_and_buildings,separate_movable_assets_and_sets_of_movable_assets,other_long_term_tangible_assets,adjustment_item_for_acquired_assets,total_long_term_financial_assets,bank_balances_with_maturity_longer_than_one_year,current_assets,inventories,non_current_claims,current_claims,trade_receivables,social_security_tax_receivables_and_grants,financial_assets,other_financial_accounts,cash_and_bank_balances,total_owners_equity_and_liabilities,owners_equity,share_capital,share_capital_and_changes_in_share_capital,claims_for_subscribed_owners_equity,capital_funds,valuation_differences,undivided_profit_or_unpaid_loss_from_previous_years,profit_for_the_reporting_period_after_tax,liabilities,long_term_liabilities_excluding_reserves_and_loans,long_term_reserves,long_term_bank_loans,total_short_term_liabilities_excluding_reserves_loans_and_advances,...,CA,CASH,CL,EQ,NCL,TA,TL,CC,INV,CF_NETTO,CF_SELFFIN,EAT,EBIT,SAL,COST,INT,YIE,L3,L2,L1,CF_CL,CASH_TA,SAL_TA,TL_SAL,INV_COST,INV_SAL,CC_SAL,TA_SAL,TL_TA,CF_TL,CL_TA,NCL_TA,EQ_TL,EQ_TA,EBIT_INT,CL_CC,ROE,EAT_TA,ROA_BRUTTO,CF_TA,CF_SAL,ROS,EAT_YIE,ROI,ROA_NETTO,LABOR_PRODUCTIVITY,SOCLIAB_SAL,sknace_division_name,sknace_division,sknace_subcategory
0,4890214,2575566,2,25527,2015-07-31,671.0,2014,1,699.0,"Kerametal, akciová spoločnosť,",1970-02-02,None,46180.0,None,12,4890214,699.0,5175248.0,216.0,0.0,0.0,0.0,0.0,0.0,0.0,216.0,0.0,5174843.0,0.0,0.0,5173364.0,5173364.0,0.0,1479.0,0.0,1479.0,5175248.0,3807863.0,10884786.0,10884786.0,0.0,-6657984.0,131090.0,131090.0,-550029.0,1367385.0,1255.0,0.0,0.0,1366130.0,...,5174843.0,1479.0,1366130.0,3807863.0,1255.0,5175248.0,1367385.0,5173364.0,0.0,-547786.0,-548266.0,-550029.0,-549549.0,6350.0,560563.0,0.0,11014.0,3.787958,3.787958,0.001083,-0.400976,0.000286,0.001227,215.336220,0.0,0.0,814.702992,293399.886614,0.264216,-0.400608,0.263974,0.000243,2.784778,0.735784,NaN,2.640700e-01,-0.144446,-0.106281,-0.106188,-0.105847,-86.265512,-86.618740,-49.939078,-0.106281,-0.106281,0.217953,6.666929,"Veľkoobchod, okrem motorových vozidiel a motoc...",G,46.0
1,5392251,2976863,2,25527,2016-12-31,671.0,2015,1,699.0,"Kerametal, akciová spoločnosť, Bratislava",1970-02-02,None,46180.0,None,12,5392251,699.0,5174845.0,222.0,0.0,0.0,0.0,0.0,0.0,0.0,222.0,0.0,5174245.0,0.0,0.0,5172377.0,5172377.0,0.0,1868.0,0.0,1868.0,5174845.0,3480567.0,10884786.0,10884786.0,0.0,-7076917.0,0.0,0.0,-327302.0,1694278.0,1255.0,0.0,0.0,1693023.0,...,5174245.0,1868.0,1693023.0,3480567.0,1255.0,5174845.0,1694278.0,5172377.0,0.0,-326822.0,-327302.0,-327302.0,-326822.0,3633.0,336975.0,0.0,10153.0,3.056217,3.056217,0.001103,-0.193040,0.000361,0.000702,466.357831,0.0,0.0,1423.720617,512783.980182,0.327407,-0.192898,0.327164,0.000243,2.054307,0.672593,NaN,3.273201e-01,-0.094037,-0.063249,-0.063156,-0.063156,-89.959262,-90.091385,-32.236974,-0.063249,-0.063249,0.000000,11.652904,"Veľkoobchod, okrem motorových vozidiel a motoc...",G,46.0
2,5887438,3375702,2,25527,2017-12-27,671.0,2016,1,699.0,"Kerametal, akciová spoločnosť, Bratislava",1970-02-02,None,46180.0,None,12,5887438,699.0,14901.0,222.0,0.0,0.0,0.0,0.0,0.0,0.0,222.0,0.0,14679.0,0.0,0.0,13645.0,13645.0,0.0,1034.0,0.0,1034.0,14901.0,-1683081.0,10884786.0,10884786.0,0.0,-7383074.0,-21145.0,-21145.0,-5163648.0,1697982.0,0.0,0.0,0.0,1697982.0,...,14679.0,1034.0,1697982.0,-1683081.0,0.0,14901.0,1697982.0,13645.0,0.0,-5163168.0,-5163648.0,-5163648.0,-5163168.0,1994.0,5166660.0,0.0,3492.0,0.008645,0.008645,0.000609,-3.040767,0.069391,0.133817,851.545637,0.0,0.0,6.843029,2690.250752,113.950876,-3.040767,113.950876,0.000000,-0.991224,-112.950876,NaN,1.244399e+02,NaN,-346.530300,-346.498087,-346.498087,-2589.352056,-2589.592778,-1478.707904,-346.530300,-346.530300,0.000000,21.230692,"Veľkoobchod, okrem motorových vozidiel a motoc...",G,46.0
3,6361460,3757740,1,25527,2018-12-17,671.0,2017,1,699.0,"Kerametal, akciová spoločnosť, Bratislava",1970-02-02,None,46180.0,None,12,6361460,699.0,14736.0,235.0,0.0,0.0,0.0,0.0,0.0,0.0,235.0,0.0,14501.0,0.0,0.0,13559.0,13559.0,0.0,942.0,0.0,942.0,14736.0,-1714376.0,10884786.0,10884786.0,0.0,-7383062.0,-5184793.0,-5184793.0,-31307.0,1729112.0,0.0,0.0,0.0,1729112.0,...,14501.0,942.0,1729112.0,-1714376.0,0.0,14736.0,1729112.0,13559.0,0.0,-30827.0,-31307.0,-31307.0,-30827.0,1993.0,33542.0,11844.0,2715.0,0.008386,0.008386,0.000545,-0.017828,0.063925,0.135247,867.592574,0.0,0.0,6.803312,2661.796287,117.339305,-0.017828,117.339305,0.000000,-0.991478,-116.339305,-1.602752,1.275250e+02,NaN,-2.124525,-2.091952,-2.091952,-15.467637,-15.708480,-11.531123,-1.320779,-2.124525,0.000000,21.241846,"Veľkoobchod, okrem motorových vozidiel a motoc...",G,46.0
4,6417420,3787505,1,25527,None,671.0,2018,1,699.0,"Kerametal, akciová spoločnosť, Bratislava",1970-02-02,None,46180.0,None,10,6417420,699.0,8862.0,233.0,0.0,0.0,0.0,0.0,0.0,0.0,233.0,0.0,8243.0,0.0,0.0,48.0,48.0,0.0,8195.0,0.0,8195.0,8862.0,-74014074.0,10884786.0,10884786.0,0.0,-7383064.0,-75702715.0,-75702715.0,-1813081.0,74022936.0,0.0,0.0,0.0,74022936.0,...,8243.0,8195.0,74022936.0,-74014074.0,0.0,8862.0,74022936.0,48.0,0.0,-1813081.0,-1813081.0,-1813081.0,-1813081.0,1543.0,1826060.0,0.0,12979.0,0.000111,0.000111,0.000111,-0.024494,0.924735,0.174114,47973.386909,0.0,0.0,0.031108,2067.608555,8352.847664,-0.024494,8352.847664,0.000000,-0.999880,-8351.847664,NaN,1.542144e+06,NaN,-204.590499,-204.590499,-204.590499,-1175.036293,-1175.036293,-139.693428,-204.590499,-204.590499,0.000000,27.436811,"Veľkoobchod, okrem motorových vozidiel a motoc...",G,46.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1679945,8105494,5156278,1,2040228,2022-05-31,54329841.0,2021,1,699.0,skdarceky s. r. o.,2021-12-31,None,46190.0,None,12,8105494,699.0,5000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5000.0,0.0,0.0,0.0,0.0,0.0,5000.0,0.0,5000.0,5000.0,5000.0,5000.0,5000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5000.0,5000.0,0.0,5000.0,0.0,5000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,0.000000,NaN,1.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,"Veľkoobchod, okrem motorových vozidiel a motoc...",G,46.0
1679946,7514307,4679250,1,1957322,2021-03-20,56488041.0,2020,12,687.0,"NOKO Land, s.r.o.",2020-12-16,None,82990.0,None,1,7514307,687.0,5000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5000.0,0.0,0.0,0.0,0.0,0.0,5000.0,0.0,5000.0,5000.0,5000.0,5000.0,5000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5000.0,5000.0,0.0,5000.0,0.0,5000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,0.000000,NaN,1.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,"Administratívne, pomocné kancelárske a iné obc...",N,82.0
1679947,4458450,2225050,1,289353,2015-02-27,60748940.0,2014,1,699.0,VALPEX s.r.o.,1991-07-17,None,46900.0,None,12,4458450,699.0,69884.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,69384.0,0.0,0.0,21566.0,21566.0,0.0,47818.0,0.0,47818.0,69884.0,-5515.0,0.0,0.0,0.0,0.0,-3797.0,-3797.0,-1718.0,75399.0,70059.0,0.0,0.0,5008.0,...,69384.0,47818.0,5008.0,-5515.0,70391.0,69884.0,75399.0,21566.0,0.0,-758.0,-1718.0,-1718.0,-758.0,174779.0,179373.0,2.0,178615.0,13.854633,13.854633,9.548323,-0.151358,0.684248,2.500987,0.431396,0.0,0.0,0.123390,143.943151,1.078916,-0.010053,0.071662,1.007255,-0.073144,-0.078916,-378.000000,2.322174e-01,NaN,-0.024584,-0.010847,-0.010847,-0.004337,-0.009830,-0.009618,-0.024555,-0.024584,0.095681,0.006934,"Veľkoobchod, okrem motorových vozidiel a motoc...",G,46.0
1679948,5030426,2678436,1,289353,2016-03-12,60748940.0,2015,1,699.0,VALPEX s.r.o.,1991-07-17,None,46900.0,None,12,5030426,699.0,30029.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29950.0,0.0,0.0,3989.0,3989.0,0.0,25961.0,0.0,25961.0,30029.0,-9614.0,0.0,0.0,0.0,0.0,-5515.0,-5515.0,-4099.0,39643.0,37633.0,0.0,0.0,2010.0,...,29950.0,25961.0,2010.0,-9614.0,37633.0,30029.0,39643.0,3989.0,0.0,-3139.0,-4099.0,-4099.0,-3139.0,120316.0,126841.0,3.0,123702.0,14.900498,14.900498,12.915920,-1.561692,0.864531,4.006660,0.329491,0.0,0.0,0.033154,89.850394,1.320157,-0.079182,0.066935,1.253222,-0.242514,-0.320157,-1045.333333,5.038857e-01,NaN,-0.136501,-0.104532,-0.104532,-0.026090,-0.034069,-0.033136,-0.136401,-0.136501,0.074570,0.000000,"Veľkoobchod, okrem motorových vozidiel a motoc...",G,46.0
1679949,4673569,2406230,1,1040443,None,63987538.0,2014,1,687.0,VTS Czech Republic s.r.o.,1999-01-21,None,74900.0,None,12,4673569,687.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23144.0,23144.0,23144.0,23144.0,755840.0,732696.0,0.0,755840.0,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.0,0.0,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.030620,0.030620,0.030620,NaN,NaN,0.076438,0.000000,"Ostatné odborné, vedecké a technické činnosti",M,74.0

In [22]:
merged_df.to_csv('../../DATA/MODEL/financial_ratios_df.csv', index = False)